services:
  authorization-service:
    build: .
    env_file: .env
    ports:
      - "${AUTHORIZATION_SERVICE_APP_PORT}:80"
    depends_on:
      - authorization-service-db
    networks:
      - authorization-service-net
      - backend-net

  authorization-service-db:
    image: mysql:8.0
    ports:
      - "${AUTHORIZATION_SERVICE_DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${AUTHORIZATION_SERVICE_DATABASE_PASSWORD}
      MYSQL_DATABASE: ${AUTHORIZATION_SERVICE_DATABASE_DB}
      MYSQL_USER: ${AUTHORIZATION_SERVICE_DATABASE_USER}
      MYSQL_PASSWORD: ${AUTHORIZATION_SERVICE_DATABASE_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./auth-database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - authorization-service-net

volumes:
  mysql-data:

networks:
  authorization-service-net:
  backend-net:
    external: true